# Generated by Django 5.0.7 on 2024-10-21 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
