# Generated by Django 5.0.7 on 2024-11-04 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_order_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_json',
            new_name='items_json',
        ),
    ]
